name: Compiling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Compile on all supported OSes
  compile:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache-dependency-path: 'tools/go.sum'

      - name: Compile
        run: make compile-only
