name: Compiling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Compile on all supported OSes
  compile:
    strategy:
      matrix:
        go-version:
          - 1.19
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
          cache: true
          cache-dependency-path: 'tools/go.sum'

      - name: Add GOBIN to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Compile
        run: make compile-only
